name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
- uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        CEREBRATE_TOKEN: ${{ secrets.CEREBRATE_TOKEN }}
      run: |-
        python build_readme.py
        cat README.md
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "readme-bot@arkane-systems.net"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push
